#ifndef GOLDENEYE_RAMROM_PLAYBACK_SERVICE_BRIDGING_H
#define GOLDENEYE_RAMROM_PLAYBACK_SERVICE_BRIDGING_H

#include "ge_ramrom_playback_v5.h"

#endif /* GOLDENEYE_RAMROM_PLAYBACK_SERVICE_BRIDGING_H */
