var state = GoldenEyeKeyboardInputState()

state.keyDown(keyCode: 0x0D, isRepeat: false)
precondition(state.held == 1 << 3)
precondition(state.pendingPressed == 1 << 3)
state.keyDown(keyCode: 0x0D, isRepeat: true)
precondition(state.pendingPressed == 1 << 3)

let first = state.snapshot()
precondition(first.sequence == 1)
precondition(first.held == 1 << 3)
precondition(first.pressed == 1 << 3)
precondition(first.released == 0)
precondition(state.pendingPressed == 0 && state.pendingReleased == 0)

state.keyUp(keyCode: 0x0D)
let second = state.snapshot()
precondition(second.sequence == 2)
precondition(second.held == 0)
precondition(second.pressed == 0)
precondition(second.released == 1 << 3)

state.keyDown(keyCode: 0x00, isRepeat: false)
state.keyDown(keyCode: 0x02, isRepeat: false)
state.flagsChanged(keyCode: 0x38, isDown: true)
precondition(state.held == ((1 << 0) | (1 << 2) | (1 << 11)))
state.reset()
precondition(state.held == 0 && state.pendingPressed == 0 && state.pendingReleased == 0)
state.keyDown(keyCode: 0x7B, isRepeat: false)
precondition(state.held == 1 << 6)
state.keyUp(keyCode: 0x7B)
precondition(state.held == 0)
state.keyDown(keyCode: 0xFFFF, isRepeat: false)
precondition(state.held == 0)

print("keyboard_input_smoke: PASS")
